name: clapper
version: 0.1.0.0
github: "igr/clapper"
license: BSD-2-Clause
author: "Author name here"
maintainer: "example@example.com"
copyright: "2024 Oblac.dev"

extra-source-files:
  - README.md
  - CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/igr/clapper#readme>

dependencies:
  - base >= 4.7 && < 5
  - aeson
  - servant-server
  - wai
  - wai-cors
  - warp
  - uuid
  - text
  - persistent
  - persistent-template
  - persistent-sqlite
  - monad-logger
  - string-conversions
  - transformers
  - resourcet

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src

executables:
  clapper-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - base
      - clapper

tests:
  clapper-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - base
      - clapper
      - hspec
      - hspec-wai
      - hspec-wai-json
      - aeson
